### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by mcollina** [fastify/aws-lambda-fastify#105]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

v3.29.0

### Plugin version

master

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

If I clone this repository and  run `npm i` I get:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: aws-lambda-fastify@2.1.2
npm ERR! Found: fastify@3.29.0
npm ERR! node_modules/fastify
npm ERR!   dev fastify@"^3.28.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer fastify@"^2.6.0" from aws-serverless-fastify@1.0.28
npm ERR! node_modules/aws-serverless-fastify
npm ERR!   dev aws-serverless-fastify@"^1.0.28" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I'm on npm v8.5.5.

### Steps to Reproduce

see above

**Comment by climba03003** [comment]
I think nothing we can do here.
Or just remove `aws-serverless-fastify` from benchmark.
https://github.com/benMain/aws-serverless-fastify/blob/master/package.json#L70

**Comment by mcollina** [comment]
let's do that then?

**Comment by adrai** [comment]
or use --force, like here: https://github.com/fastify/aws-lambda-fastify/blob/master/.github/workflows/ci.yml#L30

**Comment by adrai** [comment]
ok, I've found an alternative solution: https://github.com/fastify/aws-lambda-fastify/commit/db86c28298b2733a33f7ee5e5f5ac1e094121c52
thanks to https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
