### ISSUE TITLE
Lax permissions in CI?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/aws-lambda-fastify#106]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Looking at `ci.yml`, the `test` job has quite lax permissions:

https://github.com/fastify/aws-lambda-fastify/blob/db86c28298b2733a33f7ee5e5f5ac1e094121c52/.github/workflows/ci.yml#L17-L18

Is there a reason this job needs these?
From reviewing the scripts it runs, I can't see any.

**Comment by adrai** [comment]
probably not, copied from the fastify repo some time ago....

**Comment by Fdawgs** [comment]
> probably not, copied from the fastify repo some time ago....

Cool beans, will open a PR. :)
