### ISSUE TITLE
Setting cookie to reply causes API Gateway v1 to return 500

### ISSUE THREAD

**Issue by jsaguet** [fastify/aws-lambda-fastify#109]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.19.1

### Node.js version

14.19.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

When setting a cookie in the reply by using `reply.setCookie()` from `@fastify/cookie` package, the proxy adds a cookie property to the lambda response.

The response payload with the cookie property does not respect API Gateway v1 format and therefore API Gateway always returns a 500 error.

Example response that causes the API Gateway V1 to error: 
```json
{
  "statusCode": 200,
  "body": "<!DOCTYPE html><html><head><title>Test</title></head><body></body></html>",
  "headers": {
    "content-type": "text/html; charset=utf-8",
    "content-length": "1024",
    "date": "Mon, 30 May 2022 16:40:00 GMT",
    "connection": "keep-alive"
  },
  "isBase64Encoded": false,
  "cookies": [
    "MY_COOKIE=value; Expires=Mon, 30 May 2022 17:00:00 GMT",
    "OTHER_COOKIE=other; Expires=Mon, 30 May 2022 17:00:00 GMT"
  ],
  "multiValueHeaders": {
    "set-cookie": [
      "MY_COOKIE=value; Expires=Mon, 30 May 2022 17:00:00 GMT",
      "OTHER_COOKIE=other; Expires=Mon, 30 May 2022 17:00:00 GMT"
    ]
  }
}
```

Example response that works well with the API Gateway V1 : 
```json
{
  "statusCode": 200,
  "body": "<!DOCTYPE html><html><head><title>Test</title></head><body></body></html>",
  "headers": {
    "content-type": "text/html; charset=utf-8",
    "content-length": "1024",
    "date": "Mon, 30 May 2022 16:40:00 GMT",
    "connection": "keep-alive"
  },
  "isBase64Encoded": false,
  "multiValueHeaders": {
    "set-cookie": [
      "MY_COOKIE=value; Expires=Mon, 30 May 2022 17:00:00 GMT",
      "OTHER_COOKIE=other; Expires=Mon, 30 May 2022 17:00:00 GMT"
    ]
  }
}
```

I tried to fiddle with the code and everything works well when I comment the following line in index.js: https://github.com/fastify/aws-lambda-fastify/blob/b9ec2486c192048c87857ef93650d31695f0cb8c/index.js#L121

Here are the response format for API Gateway: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

### Steps to Reproduce

setup a lambda behind an API Gateway v1.

call reply.setCookie('cookieName', 'value') in the lambda code

api gateway returns error 500

### Expected Behavior

`cookies` property should not be present in the lambda response payload when using API Gateway V1
Only the `Set-Cookie` headers must be present in the lambda payload response when using API Gateway V1

**Comment by adrai** [comment]
v2.1.3 should fix this

**Comment by jsaguet** [comment]
I can confirm 2.1.3 fixes the issue. Thanks

**Comment by jsaguet-betclic** [comment]
Actually @adrai, set-cookie headers are not sent anymore with 2.1.3

It seems the version property is not set in API GW v1 events. Only in v2.
So this condition is never true:
```javascript
if (multiValueHeaders && event.version === '1.0') ret.multiValueHeaders = multiValueHeaders
```

API GW v2 event: https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event-v2.json
API GW v1 event: https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event.json

**Comment by adrai** [comment]
v2.1.4 should be better

**Comment by jsaguet** [comment]
I now have the set-cookie headers with 2.1.4 when I have multiple set-cookie headers.

When setting only one set-cookie header though, it does not appear in the response.
I believe it is because of this line:
https://github.com/fastify/aws-lambda-fastify/blob/5ce40d2a94a74d8d6c83f883b67c2d9e6c3f2ce5/index.js#L107

I checking if `event.version === '2.0'` before deleting the header would work.

**Comment by adrai** [comment]
v2.1.5 ?

**Comment by jsaguet** [comment]
It works with one set-cookie header but API GW returns error 502 when setting multiple set-cookie headers 🤔

**Comment by adrai** [comment]
v2.1.6
