### ISSUE TITLE
Support compressed responses

### ISSUE THREAD

**Issue by melchor629** [fastify/aws-lambda-fastify#117]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, the only way to specify that the body is binary (ie.: encoded in base64) is by reading the `Content-Type` and match it with the `binaryMimeTypes` option. For those cases, the library will respond with the body in base64 perfectly.

But there are cases in which, the response is a text mime type (like `application/json`) but the body may be encoded in gzip or brotli (compressed).

The proposal is to look into the [`Content-Encoding`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) and treat them as binary if it is filled, here: https://github.com/fastify/aws-lambda-fastify/blob/abf31672652bf5c0cce5d5d33cd7ae5a3a3e3cdc/index.js#L113

Add an option to enable/disable this check is acceptable.

### Motivation

In our scenario, sometimes we treat with "huge" JSON payloads in both request and responses. The request body works fine compressed, but the response does not. Sometimes we face the issue in which the response is a bit huge and AWS Lambda refuses to respond, but we know that compressed it will work fine.

We use [`@fastify/compress`](https://www.npmjs.com/package/@fastify/compress) to handle with compressed payloads.

### Example

With the proposal, there is nothing to do to make it work.

**Comment by adrai** [comment]
Would you like to try a Pull Request to discuss this based on your implementation approach?

**Comment by melchor629** [comment]
Perfect, I will create the PR with some initial ideas on how to implement this.

**Comment by adrai** [comment]
addressed in **v3.1.0**
