### ISSUE TITLE
Release 3.1.0 doesn't match this repo

### ISSUE THREAD

**Issue by floric** [fastify/aws-lambda-fastify#120]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey,

I just received an update 3.1.0 from NPM but was surprised to see no matching Tag oder incremented version in the package.json. Just to be sure, everything is right: has this change been published by intention? what has been changed?

Kind regards and thanks for your work,
Florian

**Comment by adrai** [comment]
Sorry, very shitty internet connection here in our holiday village... seems the push did timeout...
It should be pushed now, also with a tag.

**Comment by Uzlopak** [comment]
Release is now visible.

The change is that now compressed data is properly base64 encoded.

Closing :)
