### ISSUE TITLE
Is there any reason the package is not written with TS?

### ISSUE THREAD

**Issue by brunozoric** [fastify/aws-lambda-fastify#122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

A question from the title of the issue :)

If you give me some guidelines, I can rewrite the package when I get few hours free.
If there are no guidelines from your side, I'm also ok with that :)

**Comment by Uzlopak** [comment]
We dont use typescript in a lot of packages, because typescript does not create the most effective and fast code. With using pure Javascript we can control what actually is happening in the code.

**Comment by brunozoric** [comment]
Ok. Closing the issue then.
