### ISSUE TITLE
Support for MultiStringQueryParameter in ApiGateway V2

### ISSUE THREAD

**Issue by maxkre96** [fastify/aws-lambda-fastify#125]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Since the API Gateway V2 does not support the field `MultiValueQueryStringParameters` (see [AWS Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)) anymore,
I would suggest to enable the framework to offer the possibility to parse comma separated query parameters to an array. 

The API Gateway V2 provides multiValueQueryStringParameters like 
`example.com?query=Value0&query=Value1` 
using a comma separated query parameter just like: 
` queryStringParameters : {  queryParameter: '"Value0,Value1" }`.

### Motivation

Enables Frameworks like nestjs to retrieve multi value queries such as <url>?value=one&value=twp to an array ['one', 'two'] without further modification just like in the API Gateway V1. It might be useful to implemented an adapter option which can be used to enable parsing comma separed query params or not.

### Example

NestJS Example:

`<url>?value='foo'&value='bar'`

Should in the future results in an query object:
`query: { value: ['foo', 'bar'] }`

Currently the above mentioned query results in the following query object:
`query: { value: 'bar' }`

NestJs for Instance can then be used with a fastify backend without further data manipulation or transformation:
`  @Get()
  getHello(@Query('value') value: string[]): string {
    return value?.toString() // Return value: ['foo', 'bar'] 
}
`

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by adrai** [comment]
maybe something like this is already sufficient:

```js
      if (event.queryStringParameters) {
        Object.keys(event.queryStringParameters).forEach((k) => {
          if (event.queryStringParameters[k] && event.queryStringParameters[k].indexOf(',') > 0) {
            event.queryStringParameters[k] = event.queryStringParameters[k].split(',')
          }
        })
      }
```

**Comment by adrai** [comment]
can you try with v3.1.2 ?

**Comment by maxkre96** [comment]
Looks good from my site. Thank you for your fast change. 

As a remark, this implementation also affects APIGatewayProxyEvents of V1. I think the version field of the event does return the APIGateway Version which makes the following possible: 

`if (event.queryStringParameters && event.version === '2.0') {
        Object.keys(event.queryStringParameters).forEach((k) => {
          if (event.queryStringParameters[k] && event.queryStringParameters[k].indexOf(',') > 0) {
            event.queryStringParameters[k] = event.queryStringParameters[k].split(',')
          }
        })
}`

However, I am not sure on that since this is poorely documented.
