### ISSUE TITLE
Do you suggest this wrapper over serverless-http?

### ISSUE THREAD

**Issue by steffenstolze** [fastify/aws-lambda-fastify#158]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey folks,

thanks for maintaining Fastify and all it's packages! Awesome work!

I've realised that we're often using https://github.com/dougmoscrop/serverless-http when running Fastify inside a Lambda function.

I was wondering, are there any downsides to this approach? Do you suggest this package, since it's in the same fastify namespace?

Thank you!

**Comment by adrai** [comment]
serverless-http seems to be slower ;-)
https://github.com/fastify/aws-lambda-fastify#%EF%B8%8Fsome-basic-performance-metrics

**Comment by steffenstolze** [comment]
@adrai sure, but at the same time you can see this in the readme:

<img width="866" alt="image" src="https://github.com/fastify/aws-lambda-fastify/assets/8490779/e94f1096-ff93-4cc3-90e6-48e48aa6d94b">

I don't quite get that tbh.. If I'm using another web framework (e.g. Fastify) I should have a look at: [serverless-http](https://github.com/dougmoscrop/serverless-http) and not the aws-lambda-fastify package for this web framework?

**Comment by steffenstolze** [comment]
This makes absolute sense now, thx!

So, you'd recommend aws-lambda-fastify then, I guess. Which would be rational, since it's the same namespace like the main web framework.

No known limitations for Fastify compared to serverless-http? Sorry for stressing that point, I don't want to discover this down the road :)

thank you!

**Comment by adrai** [comment]
Yes, I personally recommend aws-lambda-fastify. No known limitations so far.

**Comment by steffenstolze** [comment]
Thank you!
