### ISSUE TITLE
Maintainer access to the Plugins Team

### ISSUE THREAD

**Issue by gurgunday** [fastify/aws-lambda-fastify#178]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This is a [core plugin](https://github.com/fastify/fastify/blob/main/docs/Guides/Ecosystem.md#core) and the Plugins Team doesn't have access to it

CC @Uzlopak if you can change it

**Comment by Uzlopak** [comment]
@fastify/leads

**Comment by jsumners** [comment]
This is a library. It falls under the @fastify/libraries team.

**Comment by Uzlopak** [comment]
Checked, and it is part of @fastify/libraries. Closing :)
