### ISSUE TITLE
Use event.pathParameters.proxy instead of event.path

### ISSUE THREAD

**Issue by hfhchan-plb** [fastify/aws-lambda-fastify#182]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.3.1

### Node.js version

18.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.5

### Description

While migrating from serverless-express, I noticed that paths are being processed differently by aws-lambda-fastify. It seems that serverless-express will use `event.pathParameters.proxy` instead of `event.path`, which means if on API Gateway I have it configured `'v2/{proxy+}'` and I am accessing `/v2/token`, it will call the express router with the path `/token` instead of `/v2/token`.

I wonder if an additional flag can be added to replicate that behaviour?

### Steps to Reproduce

I'm using this with NestJS:

```
      const expressApp = express();
      const adapter = new ExpressAdapter(expressApp);
      await initApp(adapter, appModule);
      const server = configure({
        app: expressApp,
        binarySettings: { contentTypes: ['application/pdf', 'application/x-gzip'] },
      });
      return server;
```

vs

```
      const adapter = new FastifyAdapter();
      await initApp(adapter, appModule);
      const server = awsLambdaFastify(adapter.getInstance() as FastifyInstance, {
        binaryMimeTypes: ['application/pdf', 'application/x-gzip'],
        decorateRequest: true,
      });
      return server;
```

and NestJS with express gives me `req.route.path = '/token'` while NestJS with fastify gives me `req.routerPath = '/v2/token'`.

### Expected Behavior

Matching serverless-express or providing a flag to toggle that behaviour.

**Comment by hfhchan-plb** [comment]
Looks like that behaviour was added to serverless-express in 2021:
https://github.com/vendia/serverless-express/issues/86

**Comment by adrai** [comment]
How does the configured route look in your code? similar to https://github.com/fastify/aws-lambda-fastify/blob/master/test/basic.test.js#L23 ?
Can you create a PR with a failing test?

**Comment by adrai** [comment]
I did not test it, but it might be it would work by changing [this line](https://github.com/fastify/aws-lambda-fastify/blob/eea33fa0a30f89a8aaae1c006e619a5fcc3017ac/index.js#L42C21-L42C21) like this:

```diff
- let url = event.path || event.rawPath || '/' // seen rawPath for HTTP-API
+ let url = (event.pathParameters && event.pathParameters.proxy && `/${event.pathParameters.proxy}`) || event.path || event.rawPath || '/' // seen rawPath for HTTP-API
```

Can you test this?

**Comment by hfhchan-plb** [comment]
Yes that works, but I'm not sure how it should interact with `retainStage`.

**Comment by adrai** [comment]
Can you please provide a new test case based on your example?
How does your event look like?

**Comment by adrai** [comment]
Just released v3.4.0 that should work. see https://github.com/fastify/aws-lambda-fastify/commit/692678217a67387a7f2a74d7984b37765acfb2e1
In case this does not work for you, please provide a new test case.

**Comment by hfhchan-plb** [comment]
>  How does your event look like?

```
{
  "body": null,
  "headers": {},
  "httpMethod": "GET",
  "isBase64Encoded": false,
  "multiValueHeaders": {},
  "multiValueQueryStringParameters": null,
  "path": "/data/token",
  "pathParameters": { "proxy": "data/token" },
  "queryStringParameters": null,
  "requestContext": {
    "path": "/v2/data/token",
    "protocol": "HTTP/1.1",
    "resourcePath": "/prod/v2/{proxy*}",
    "stage": "prod"
  },
  "resource": "/v2/{proxy+}",
  "stageVariables": null
}
```

**Comment by adrai** [comment]
Oh, yes I forgot the types...
v3.4.2 should address this
