### ISSUE TITLE
Remote IP address passed to app.inject()

### ISSUE THREAD

**Issue by steveatkoan** [fastify/aws-lambda-fastify#186]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi
How possible is it to get the remote IP from the aws lambda environment (somewhere?) and include that in the app.inject() call? 

### Motivation

I'm using fastify/rate-limit because I want custom control over the rate limits applied. But because I don't know the remote IP address it thinks the whole world is 127.0.0.1 when a request comes from api gateway / lambda

**Comment by steveatkoan** [comment]
you should be able to look at the request.awsLambda.event.identity.sourceIp or request.awsLambda.event.http.sourceIp
Depending on if we are using the REST api or HTTP api gateway respectively.
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event.json
https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event-v2.json

**Comment by adrai** [comment]
the remote address should be  in the x-forwarded-for header

**Comment by adrai** [comment]
v3.5.0 should also use the sourceIp as remoteAddress

**Comment by pavarnos** [comment]
So fast! Thanks heaps. Very helpful!

**Comment by steveatkoan** [comment]
Thank you
