### ISSUE TITLE
Add easier support for callbackWaitsForEmptyEventLoop

### ISSUE THREAD

**Issue by ShogunPanda** [fastify/aws-lambda-fastify#26]
## 🚀 Feature Proposal

In order to make AWS works properly with mixed callback/async invocation, one might need to modify `context.callbackWaitsForEmptyEventLoop`.

Nowadays, it is possible with a code like this:

```js
const proxy = awsLambdaFastify(app)

exports.handler = function(event, context, callback) {
  context.callbackWaitsForEmptyEventLoop = false
  return proxy(event, context, callback)
}
```

But it would be great if it can directly provided as option. See below.

Note that in the implementation checking of the property should be done with `options.hasOwnProperty` or similar, since both truthy and falsy values are acceptable.

## Motivation

To make typical use case easier to manage and without boilerplate code.

## Example

```js
exports.handler = awsLambdaFastify(app, {callbackWaitsForEmptyEventLoop: false})
```

**Comment by adrai** [comment]
cool idea... landed in v1.0.4
