### ISSUE TITLE
Missing support for API Gateway "multiValueQueryStringParameters"

### ISSUE THREAD

**Issue by hakimio** [fastify/aws-lambda-fastify#29]
It seems aws-lambda-fastify is missing support for "multiValueQueryStringParameters" introduced in API Gateway in November last year.
References:
[AWS Blog](https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/)
[AWS Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format)
[serverless-http](https://github.com/dougmoscrop/serverless-http/pull/70)
[Serverless offline](https://github.com/dherault/serverless-offline/pull/515)

**Comment by adrai** [comment]
Can you create a test case here: https://github.com/fastify/aws-lambda-fastify/blob/master/test/basic.test.js ?

**Comment by hakimio** [comment]
Sure, I'll do that.

**Comment by hakimio** [comment]
@adrai See PR #30

**Comment by hakimio** [comment]
@adrai You might also want to remove the hack for headers with the same name and add proper support using [multiValueHeaders](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format).
