### ISSUE TITLE
AWS WebSocket API(s) are not supported?

### ISSUE THREAD

**Issue by el2ro** [fastify/aws-lambda-fastify#46]
I was trying to use aws-lambda-fastify with NestJs framework for the HTTP API WebSocket endpoints but it quite does not seem to work.

Quick browse indicates that WS endpoints are not supported?

```
Error: should have required property '.url',should have required property '.path',should match exactly one schema in oneOf
    at doInject (/serverless/.build/cloud/node_modules/light-my-request/index.js:85:13)
    at inject (/serverless/.build/cloud/node_modules/light-my-request/index.js:74:12)
    at Object.inject (/serverless/.build/cloud/node_modules/fastify/fastify.js:342:14)
    at /serverless/.build/cloud/node_modules/aws-lambda-fastify/index.js:39:9
    at new Promise (<anonymous>)
    at /serverless/.build/cloud/node_modules/aws-lambda-fastify/index.js:38:16
    at /serverless/cloud/src/serverless.ts:77:10
    at step (/serverless/.build/cloud/src/serverless.js:33:23)
    at Object.next (/serverless/.build/cloud/src/serverless.js:14:53)
    at /serverless/.build/cloud/src/serverless.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/serverless/.build/cloud/src/serverless.js:4:12)
    at exports.handler (/serverless/cloud/src/serverless.ts:70:19)
    at InProcessRunner.run (/serverless/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:100:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by adrai** [comment]
Never used Websockets so far...
How would a setup look like?
AWS part + code part?
Can you elaborate?

**Comment by el2ro** [comment]
Quick setup can be found from here https://github.com/el2ro/nest-serverless

**Comment by adrai** [comment]
I’m not familiar with nest...
How does a lambda websocket event look like? How should this be mapped to fastify.inject method?

**Comment by el2ro** [comment]
General info about the AWS WebSocket gateway can be found from https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html

When WS endpoints are used in Lambda it should be pretty close to HTTP Api endpoints. There are some changes tought. I guess there is no url and maybe not a path, but route / action.

**Comment by adrai** [comment]
As said... using the fastify.inject function...
Never used websockets with fastify and api-gateway so far...
Feel free to contribute and try a PR.

**Comment by el2ro** [comment]
I guest this is not a bug, but more likely a feature request.

**Comment by adrai** [comment]
imo, handling the websocket events in aws-lambda-fastify is a bit strange...
the fastify user is probably used to work with something like: https://github.com/fastify/fastify-websocket...
I will personally not implement and maintain something I do/did not personally use...
As said, feel free to try a PR...

**Comment by el2ro** [comment]
> The fastify users are probably used to work with something like: https://github.com/fastify/fastify-websocket...

Well I think in AWS's WS API gateway is hiding WS out from the lambda and it looks almost like HTTP API calls. I changed aws-lambda-fastify to aws-serverless-fastify and that seems to work. I can update my example to git.

I don't have time to fix this now...

**Comment by adrai** [comment]
Strange that works... it accesses the same .path property: https://github.com/benMain/aws-serverless-fastify/blob/5d1f8705e9caf4aac769c79a4cc3ea29e89c8478/src/request-mapper.ts#L29

**Comment by adrai** [comment]
I just added a path fallback to /
Released in v1.4.4
Nevertheless, I don't understand who is setting up the fastify routes in your example...
in your example, some library (probably nest) is registering a GET route for the / path (is this a convention?)
So it must be "GET /" ?

**Comment by adrai** [comment]
@el2ro Is v1.4.4 ok for you?

**Comment by el2ro** [comment]
Yes, I can confirm this "fixes" the issue but, it is true there is no support for handling different types of routes but all defaults to "GET /". So it works better but as good / bad as serverless-fastify.

I would still need to figure out how to handle route properly. Here are my studies so far:

When having new WS-client / connection API will call Lambda with
`event.requestContext.eventType: "CONNECT"
`event.requestContext.routeKey: "$connect"`

When receiving new WS message API will call Lambda with:
`event.requestContext.eventType: "MESSAGE"
`event.requestContext.messageDirection: "IN"`
`event.requestContext.routeKey: "$default"`

Or receiving WS message having { action: "testpath", message: "asdfasd"}
`event.requestContext.routeKey: "testpath"`
`event.body: {action: "testpath", message: "asdfasd"}`

When WS-client disconnected API will call lambda with:
`event.requestContext.eventType: "DISCONNECT"
`event.requestContext.routeKey: "$disconnect"`

**Comment by el2ro** [comment]
I think handling WS communication is out of scope aws-labda-fastify as this now works as good as others, this can be now closed.
