### ISSUE TITLE
Make API Gateway authorizer context available

### ISSUE THREAD

**Issue by mtranter** [fastify/aws-lambda-fastify#47]
## 🚀 Feature Proposal

AWS Api Gateway custom authorizers offer the ability to pass context data down stream to the handling lambda functions.
Currently there is no way to access this data from within fastify handlers.

## Motivation

Access authorization context data from within fastify handlers.

## Example

Looking at the existing implementation, I suggest something like the below would work:
```javascript
const authContextHeader = request.headers["x-apigateway-auth-context"];
const authContext = authContextHeader ? JSON.parse(authContextHeader) : null;
```

**Comment by mtranter** [comment]
Please ignore. 

I found the relevant code: `headers['x-apigateway-event'] = encodeURIComponent(JSON.stringify(event))`

**Comment by adrai** [comment]
👍 https://github.com/fastify/aws-lambda-fastify#hint
