### ISSUE TITLE
Clean up function like onClose hook

### ISSUE THREAD

**Issue by cjaewon** [fastify/aws-lambda-fastify#48]
## 🚀 Feature Proposal

Hello, I am currently working with aws-lambda-fastify.
I think is good that if it has a clean up function for database disconnect, etc..

## Motivation

I created a plugin for connecting a database and registered it.

As a result, I riched time out error, because I didn't disconnect a database server.
so I tried an onClose hook but it does not work :(

I thought it is good if aws-lambda-fastify has an option or any hooks similar to the onClose hook for the disconnect.

## Example

I dont know its possible but my idea is such as below code
```js
const proxy = serverlessFastify(app, {
  closeup: (fastify, done) => {
    fastify.connection.close();
    done();
  }
});
```

**Comment by adrai** [comment]
There is the possibility to intercept the callback:

```js
const awsLambdaFastify = require('aws-lambda-fastify')
const app = require('./app')

const proxy = awsLambdaFastify(app)
exports.handler = (event, context, callback) => proxy(event, context, (err, ret) => {
  callback(err, ret);
})
```

As an alternative you could also use the onResponse hook of fastify: https://www.fastify.io/docs/latest/Hooks/#onresponse

**Comment by cjaewon** [comment]
oh first one looks good to me, Thank you
