### ISSUE TITLE
Cookies are not handled

### ISSUE THREAD

**Issue by zekth** [fastify/aws-lambda-fastify#50]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Plugin version

1.4.4

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Lambda OS

### Description

In the lamda event cookies are in the `cookies` property and not in header. See:
```json
{
...
"cookies":["FOO=Bar"]
...
}
```
But in the current state we don't map this value. Also in the current context i'm using API Gateway V2

### Steps to Reproduce

Send cookies within Api Gateway v2

**Comment by adrai** [comment]
thank you @zekth, it's included in v1.5.0
