### ISSUE TITLE
Feature: Optimized mode

### ISSUE THREAD

**Issue by zekth** [fastify/aws-lambda-fastify#54]
## 🚀 Feature Proposal

Those 2 instructions are slowing down the processing of queries: https://github.com/fastify/aws-lambda-fastify/blob/master/index.js#L31-L32

What about using  https://github.com/fastify/fast-json-stringify based on this definition: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

I'd add a flag `optimized` or something similar with default value to `false` to avoid side effects.

## Motivation

Speeding up the API

## Example

```js
const awsLambdaFastify = require('aws-lambda-fastify')
const app = require('./app')

const proxy = awsLambdaFastify(app, {optimized:true})

exports.handler = proxy
```

**Comment by adrai** [comment]
Maybe there is a possibility to not introduce the optimized flag at all?
Would you like to send a Pull Request to try this? Remember to add tests.
btw: make sure v2 and v1 of the event format is supported

**Comment by zekth** [comment]
> Maybe there is a possibility to not introduce the optimized flag at all?
> Would you like to send a Pull Request to try this? Remember to add tests.
> btw: make sure v2 and v1 of the event format is supported

The `optimizeFlag` is more about offering the possibility of not using the definined schema in the case of a AWS api change. Like not serializing an extra field for example.

Are those json good references?
 - v1 https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event.json
 - v2 https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event-v2.json

Sure i can work on it

**Comment by adrai** [comment]
> 
> Are those json good references?
> 

Probably yes, but I always check the official page: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
![image](https://user-images.githubusercontent.com/1086194/121695275-3453a180-cacb-11eb-9dd6-227561992270.png)

**Comment by acorbel** [comment]
To go a little bit further, do you think we can use the `optimizeFlag` to prevent those headers to be added?
I'm working with lambda+fastify with multiple clients, we rarely use them (apart when authorizers are used). 

What do you think about it?

**Comment by adrai** [comment]
If you want to omit them, then we should introduce an additional option.

**Comment by adrai** [comment]
if fast-json-stringify can also handle new properties (and format versions) not defined in the schema (just slower), then we could replace JSON.stringify completely.
And only introduce a flag to omit the stringification completely.

**Comment by zekth** [comment]
> To go a little bit further, do you think we can use the `optimizeFlag` to prevent those headers to be added?
> I'm working with lambda+fastify with multiple clients, we rarely use them (except when authorizers are used).
> 
> What do you think about it?

You can just do:
```js
import awsLambdaFastify from 'aws-lambda-fastify';
import app from './app';

const proxy = awsLambdaFastify(app);
const f = function (event, context, callback) {
  delete event.headers;
  return proxy(event, context, callback);
};
module.exports.handler = f;
```

**Comment by adrai** [comment]
Sorry, I don't get what you want to say....

**Comment by adrai** [comment]
v1.6.0 introduced the `serializeLambdaArguments` option
