### ISSUE TITLE
Doesn't work if callback parameter is passed but it's used as an asynchronous handler

### ISSUE THREAD

**Issue by rdsedmundo** [fastify/aws-lambda-fastify#61]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.0

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

The Lambda environment always defines the `callback` parameter even if the function is marked as `async`. [This check](https://github.com/fastify/aws-lambda-fastify/blob/master/index.js#L87) is causing `serverless-offline` to break because the handler returns `undefined` if the callback parameter is passed, as the function is used asynchronously [but the callback parameter is there]. 

I also decorate my function with an external handler from Sentry and they require the callback parameter to be passed downstream, I can't be sure whether or not their code will rely on it.

### Steps to Reproduce

1. Create blank Lambda with content:
```
module.exports = async (event, context, callback) {
  console.log(callback);
  return Promise.resolve();
}
```
2. Check that it outputs:
```
[Function (anonymous)]
```

I don't think this check makes sense if the Lambda environment always passes this environment. Am I missing something?

**Comment by adrai** [comment]
So if I understood correctly, having a `return prom` after `prom.then` would solve this?

**Comment by rdsedmundo** [comment]
Yes, that's what I thought. Do you think that this would be a breaking change anyhow?

I tested this Lambda in AWS:
```
exports.handler = async (event, context, callback) => {
    await Promise.resolve();
    callback(null, 'callback_return');
    return 'regular_return';
};
```

And it works without errors, the `callback_return` is the 'winning' output in this case.

So here in `aws-lambda-fastify` if the return is added I don't think it would change the current behavior.

**Comment by adrai** [comment]
should be fine with v1.7.1
