### ISSUE TITLE
NestJS-Fastify

### ISSUE THREAD

**Issue by cefamax** [fastify/aws-lambda-fastify#62]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x

### Plugin version

1.7.1

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10

### Description

when use const proxy = awsLambdaFastify(cachedNestApp.instance);
there's an error on awsLambdaFastify
<<Type 'typeof import(".../node_modules/aws-lambda-fastify/index")' has no call signatures.ts(2349)>>

nestjs/core version 7.6.15

### Steps to Reproduce

1 Create nestjs project with fastify
2. npm install aws-lambda -D
3. npm install aws-lambda-fastify
4. Add lambda.ts on scr path
`import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { AppModule } from './app.module';
import { FastifyServerOptions, FastifyInstance, fastify } from 'fastify';
import * as awsLambdaFastify from 'aws-lambda-fastify';
import { Context, APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { Logger } from '@nestjs/common';

interface NestApp {
    app: NestFastifyApplication;
    instance: FastifyInstance;
}

let cachedNestApp: NestApp;

async function bootstrapServer(): Promise<NestApp> {
    const serverOptions: FastifyServerOptions = { logger: true };
    const instance: FastifyInstance = fastify(serverOptions);
    const app = await NestFactory.create<NestFastifyApplication>(
        AppModule,
        new FastifyAdapter(instance), { logger: !process.env.AWS_EXECUTION_ENV ? new Logger() : console }
    );
    app.setGlobalPrefix(process.env.API_PREFIX);
    await app.init();
    return { app, instance };
}

export const handler = async (event: APIGatewayProxyEvent, context: Context,): Promise<APIGatewayProxyResult> => {
    if (!cachedNestApp) {
        cachedNestApp = await bootstrapServer();
    }
    const proxy = awsLambdaFastify(cachedNestApp.instance);
    return proxy(event, context);
};`

**Comment by adrai** [comment]
Sorry, not using Nestjs and not using typescript myself...
Not really able to help, sorry.
Best would be if you could create a reproducible repository, that can be executed locally.

**Comment by cefamax** [comment]
Thanks, this is the repository with error
https://github.com/cefamax/aws-lambda-fastify-problems
you can run "npm run build" after "npm install"

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/124742209-c5783580-df1c-11eb-85a4-55cd282887ec.png)

**Comment by cefamax** [comment]
In this case i have this error when handler function is invoke
(node:28788) UnhandledPromiseRejectionWarning: TypeError: aws_lambda_fastify_1.default is not a function
    at Object.handler (c:\Dev\dotnet.lav\PDFReady\admin\dist\lambda.js:34:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by adrai** [comment]
To me this looks like a TypeScript problem...
I'm not a TypeScript user, but:

setting `esModuleInterop` to `true` fixes it:
![image](https://user-images.githubusercontent.com/1086194/124752604-586a9d00-df28-11eb-8ced-c05777f1526f.png)

alternatively, you can also do this:
![image](https://user-images.githubusercontent.com/1086194/124752800-98318480-df28-11eb-8676-feb0a06ed50e.png)

**Comment by cefamax** [comment]
Great!!! It works.
Thanks!!!!Thanks!!!!Thanks!!!!Thanks!!!!

Have a nice day!!!
