### ISSUE TITLE
aws lambda fastify takes 10X longer than http-serverless with firestore

### ISSUE THREAD

**Issue by Cosbgn** [fastify/aws-lambda-fastify#63]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.19

### Plugin version

1.7.1

### Node.js version

14.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

My app become so slow that it was barely usable. At the end I managed to pinpoint the error to aws-lambda-fastify.
A normal call to a firestore database which usually takes ~ 300ms with aws-lambda-fastify takes 3.000ms.

### Steps to Reproduce

I've created a reproduction repo here:

Simply visit this url and you will see the timings for different calls. The one which changes drastically is the one connecting to firebase. 

https://nuxt-lambdax.vercel.app/

You can view the code at https://github.com/Cosbgn/nuxt_lambda/tree/master/api

### Expected Behavior

aws-lambda-fastify should be faster or as fast as http-serverless.

**Comment by Cosbgn** [comment]
The endpoint which are identicals (but one uses aws-lambda-fastify and the other one user http-serverless) are:

- https://nuxt-lambdax.vercel.app/api/http/await
- https://nuxt-lambdax.vercel.app/api/fastify/await

For simplicity on the homepage (https://nuxt-lambdax.vercel.app) you have all the times tracked at each request (Fastify is approximately 10X slower)

**Comment by adrai** [comment]
afk, but I suspect, this is because of something else, maybe the faststify usage... 
it would be nice if you could debug if this also happens with fastify only on localhost.

**Comment by Cosbgn** [comment]
Hi @adrai this doesn't happen on localhost. 
On local it runs as fast as http-serverles, in approx 300ms.

**Comment by adrai** [comment]
The try to fork aws-lambda-fastify and debug it...
It's just 1 file... there's no real magic 😉

**Comment by Cosbgn** [comment]
I've also deploy it to `Netlify` to be sure it's not a platform problem: https://nuxt-lambdax.netlify.app - Same results, it runs 10X slower

**Comment by adrai** [comment]
If it's not a platform dependent issue, then you may try to reproduce it on localhost... i.e. by doing something like this:

```js
'use strict';
const fastify = require('fastify')
const awsLambdaFastify = require('./')

const app = fastify()
// app.setErrorHandler(async (error, req, reply) => handle_errors(error, req, reply))

app.route({
  url: '/api/fastify',
  method: ['GET'],
  preHandler: [],
  handler: async (req, reply) => {
    const name = 'Joe'
    return `Utils says hi to ${name}`
  }
})

app.route({
  url: '/api/fastify/await',
  method: ['GET'],
  preHandler: [],
  handler: async (req, reply) => {
    // const reports = await get_all('users') || []
    const reports = []
    return {
      message: `I found ${reports.length}`
    }
  }
})

exports.handler = awsLambdaFastify(app)

;(async () => {
  const ret = await exports.handler({
    httpMethod: 'GET',
    path: '/api/fastify/await',
    headers: {},
    queryStringParameters: '',
    requestContext: {
      resourcePath: '/api/fastify/await',
      stage: 'dev'
    }
  })
  console.log(ret)
})()

```

**Comment by climba03003** [comment]
Is the problem exist on consecutive call on same endpoint? Or only the first time?

**Comment by mcollina** [comment]
This is a weird bug.

The problem does not show for the hello world case:

```
/api/just-lambda: 323ms
{ "resp": { "message": "Utils says hi to I found 6" }, "time": 323, "route": "/api/just-lambda" }

/api/fastify: 146ms
{ "resp": "Utils says hi to Hello", "time": 146, "route": "/api/fastify" }

/api/http: 152ms
{ "resp": "Utils says hi to Hello", "time": 152, "route": "/api/http" }

/api/fastify/await: 2824ms
{ "resp": { "message": "Utils says hi to I found 6" }, "time": 2824, "route": "/api/fastify/await" }

/api/http/await: 281ms
{ "resp": { "message": "Utils says hi to I found 6" }, "time": 281, "route": "/api/http/await" }
```

I'm totally not sure why this is happening.

**Comment by Cosbgn** [comment]
> Is the problem exist on consecutive call on same endpoint? Or only the first time?
> 
> I assume the problem may related to boot up time, `fastify` needs some time to boot up for the `fast` response later on.

It happens at every single call, I don't think it's related to boot time or cold-start since that should apply also to `serverless-http` You can reload the page https://nuxt-lambdax.vercel.app and see that it takes always much longer than http-serverless or the simple lambda.

**Comment by adrai** [comment]
Like already suggested, best will be if you fork aws-lambda-fastify and debug it...

You may also want to check
If there is a difference when setting `serializeLambdaArguments` to `false`.

**Comment by adrai** [comment]
@Cosbgn just tried to reproduce it, by running a local firestore emulator: `gcloud beta emulators firestore start --host-port=localhost:8081`
and lambda-local: `FIRESTORE_EMULATOR_HOST=localhost:8081 lambda-local -l ./api/fastify.js -h handler --watch 8008`
But, I could not reproduce your issue.

**Comment by Cosbgn** [comment]
@adrai I can't reproduce it on local aswell. It happens only on AWS Lambda regardless on the platform. Anyways I was just hoping someone would know or spot something, if not I'll just keep on trying to debug it on local or just switch to `http-serverless`. If I find a solution or something new I'll post it here. Thanks!

**Comment by Eomm** [comment]
Could you use the `cachedFirestore` var?
It seems not used: just to check if a connection issue

Moreover, did you try the `callbackWaitsForEmptyEventLoop` parameter?


I would disable this check
https://github.com/fastify/aws-lambda-fastify/blob/5e0f18c13a0a2c9407337ba17b6c06463bc4c5f3/index.js#L32

I don't see any more differences with serverless-http

https://github.com/dougmoscrop/serverless-http/blob/f72fdeaa0d25844257e01ff1078585a92752f53a/lib/framework/get-framework.js#L56

**Comment by Cosbgn** [comment]
I've done a few more tests and indeed the problem seems to be with `callbackWaitsForEmptyEventLoop` - with that disables response times seem normal even when firestore is not cached! 🎉 => https://nuxt-lambdax.vercel.app

**Comment by adrai** [comment]
So not an issue with aws-lambda-fastify, right?

**Comment by Cosbgn** [comment]
Yes probably not an issue, I think `callbackWaitsForEmptyEventLoop` is true because on AWS is true by defaults. I don't know if it makes sense to have it false to avoid potential issues, many could be facing the same problem but they just don't realize it (they simply think the app is slow because of cold-start etc, which is not the case.)

Apparently from [this issue](https://github.com/dougmoscrop/serverless-http/issues/95) `serverless-http` doesn't use callbackWaitsForEmptyEventLoop at all somehow.

In any case I'm happy it's fixed for me, I'll close this issue. Thanks a lot everyone.
