### ISSUE TITLE
Support for event/context to decorate request

### ISSUE THREAD

**Issue by barticus** [fastify/aws-lambda-fastify#76]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently to capture the raw APIGW event or context, we need to use the json serialized headers.
While this is workable, I was wondering if its possible instead to provide an option to decorate the request with the event and context.

This would be useful to pull out [authorizer results](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) and other APIGW specific fields, and possibly reduce the overhead of json serialization (and deserialization) to read these fields.

I'm a little unsure how to go about this as this library uses Inject and is not a Plugin, but i'm happy to give it a go if you can give some guidance :)

### Motivation

Take advantage of API Gateway functionality with less computational complexity.

### Example

```
const proxy = awsLambdaFastify(app, {
 decorateRequest: true
})
```

or

```
const proxy = awsLambdaFastify(app, {
 requestDecoration: {
  enabled: true,
  eventKey: 'apiGatewayEvent',
  contextKey: 'apiGatewayContext',
 }
})
```

**Comment by adworacz** [comment]
+1 - It would be nice to not do the decoding/deserializing and access the raw values directly on the request somehow.

**Comment by mcollina** [comment]
@adrai I actually missed this comment! This is actually a good idea and it would be cool to have a PR.

**Comment by adrai** [comment]
Sorry, but I have currently no idea how this could work without passing them in some serialized way. Like @barticus already said, this is not a plugin. 🤷‍♂️

**Comment by adworacz** [comment]
Not sure if it can apply here, but I recently saw that `nestjs-pino` does some fancy tricks with AsyncLocalStorage to maintain references to request data for logging purposes without passing request objects around. Not sure if the same could be used here to workaround any not-plugin limitations.

* https://github.com/iamolegga/nestjs-pino
* https://nodejs.org/api/async_context.html#async_context_class_asynclocalstorage

**Comment by mcollina** [comment]
I would not use AsyncLocalStorage as it is quite costly.

I see two ways of doing this:

1) store it in a module-global. There is only one request at any time anyway. Then we export a function to get the value. It's important that the value is cleared as the last thing to return it to Lambda.

2) given that we receive the Fastify app, we can call `decorateRequest` on it and decorate it with the said function.

**Comment by adrai** [comment]
I've created a PR, this way we can discuss it based on that.
Feel free to review it, and let me know what you do think about it.
