### ISSUE TITLE
Question: Does this support AWS ALB?

### ISSUE THREAD

**Issue by kevbook** [fastify/aws-lambda-fastify#8]
This removes the 30 second API Gateway limitation. 
https://aws.amazon.com/about-aws/whats-new/2018/11/alb-can-now-invoke-lambda-functions-to-serve-https-requests/

**Comment by adrai** [comment]
Never tried, but if the lambda event looks the same, it should just work.
Here you can see which properties are currently used from the lambda event: https://github.com/fastify/aws-lambda-fastify/blob/master/test/basic.test.js#L98

**Comment by kevbook** [comment]
Here is the format from ALB

```js
{
  "requestContext": {
    "elb": {
      "targetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:targetgroup/something"
    }
  },
  "httpMethod": "GET",
  "path": "/abc/xyz",
  "queryStringParameters": {},
  "headers": {
    "accept": "*/*",
    "accept-encoding": "gzip, deflate",
    "accept-language": "en-us",
    "connection": "keep-alive",
    "host": "something",
    "user-agent": "976 Darwin",
    "x-amzn-trace-id": "Root=1-5d485de1",
    "x-forwarded-for": "",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "http"
  },
  "body": "",
  "isBase64Encoded": false
}
```

**Comment by adrai** [comment]
looks good, shoukd work

**Comment by adrai** [comment]
as soon as you confirm we can add this somewhere in the readme

**Comment by jsumners** [comment]
@kevbook what did you learn?

**Comment by adrai** [comment]
@kevbook can you already confirm if it works with ALB?

**Comment by kevbook** [comment]
I?ll have time on Tuesday to finish this.
Karan

On Sun, Aug 25, 2019 at 8:30 AM, Adriano Raiano <notifications@github.com> wrote:

@kevbook<https://github.com/kevbook> can you already confirm if it works with ALB?

?

**Comment by adrai** [comment]
@kevbook any news?

**Comment by adrai** [comment]
@kevbook any news?

**Comment by artu-ole** [comment]
I've tested this, works with ALB out of the box 👍

**Comment by adrai** [comment]
AWESOME!!!
thx
