### ISSUE TITLE
original event body is not available on req.awsLambda.event

### ISSUE THREAD

**Issue by dave-at-clear** [fastify/aws-lambda-fastify#95]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2

### Plugin version

2.1.0

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2.1

### Description

Hello! 👋 

The original event's body is being removed from the decorated `req.awsLambda.event.body`. This seems like the most likely cause: https://github.com/fastify/aws-lambda-fastify/blob/master/index.js#L62

Since `currentAwsArguments.event` is assigned directly to the event from the handler, setting event.body to undefined would also impact the reference held by `currentAwsArguments`.

I believe this should either assign a deep copy of the event to `currentAwsArguments.event`, or at the very least not set event.body to undefined (though it's not clear to me why this is being done).

### Steps to Reproduce

1. issue a POST request with a body included
2. Observe that the body is provided in `req.body` but `req.awsLambda.event.body` is undefined

### Expected Behavior

`req.awsLambda.event.body` contains the original post body of the event

**Comment by adrai** [comment]
v2.1.1 has just been released ;-)
