### ISSUE TITLE
Support of Set-Cookie in HTTP API V2 Response

### ISSUE THREAD

**Issue by ACenterA** [fastify/aws-lambda-fastify#97]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

To return set-cookies using the HTTP API (Lambda 2.0) the response must have n 'cookie' object. at : https://github.com/fastify/aws-lambda-fastify/blob/731c956629839bb08affdc897fc32fbb2de1381b/index.js#L110

[](https://stackoverflow.com/posts/68994753/timeline)2

To customize the response, your Lambda function should return a response with the following format.

{
    "cookies" : ["cookie1", "cookie2"],
    "isBase64Encoded": true|false,
    "statusCode": httpStatusCode,
    "headers": { "headername": "headervalue", ... },
    "body": "Hello from Lambda!"
}
So just return cookies: ['name=value', 'name=value']

Source: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.v2

### Motivation

Support HTTP API V2 Lambda 2.0

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by adrai** [comment]
v2.1.2
